version: '3'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: express
    volumes:
      - ./data:/app/data  # 데이터 유지
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express
    container_name: nginx
